server:
  port: 8080
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认 true，集群必须设置为 true
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka,
  instance:
    instance-id: order80 # 在 Eureka 中显示 instance 名
    prefer-ip-address: true  # 访问路径可以显示IP地址
#    Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以 debug 级别监控 org.example.springcloud.service.PaymentService 接口
    org.example.springcloud.service.PaymentService: debug

feign:
  hystrix:
    enabled: true # If true, an OpenFeign clint will be wrapped with a Hystrix circuit break.